version: '2'

services:
  web:
    build: web
    ports:
      - "4200:4200"
    volumes:
      - "./web:/treehouse"

  app:
    build: app
    ports:
      - "3001:3001"
    volumes:
      - "./app:/treehouse"
    links:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
